<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <TreatWarningsAsErrors Condition="'$(Configuration)' == 'Release'">true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <Authors>Twila Digital</Authors>
    <Company>Twila Digital</Company>
    <Product>Parcele+ .NET SDK</Product>
    <Copyright>Copyright (c) Twila Digital</Copyright>
    <PackageProjectUrl>https://github.com/Twila-Digital/twila-parcelemais-dotnet-sdk</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Twila-Digital/twila-parcelemais-dotnet-sdk</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>
